name: MobWars
version: 0.1a
main: me.bzvol.mobwars.MobWarsPlugin
api-version: 1.18
author: Benjámin Zvolenszki
description: Mobwars-like minigame
commands:
  mw:
    description: "The main command, read usage here: https://github.com/bzvol/mobwars"