name: MobWars
version: 0.1a
main: me.bzvol.mobwars.MobWarsPlugin
api-version: 1.18
author: Benjámin Zvolenszki
description: Mobwars-like minigame
commands:
  mw:
    description: mindenes mobwars parancs
    usage: itt valami valamiért false-ot dobott vagy nem